### ISSUE TITLE
Clean up runBlock, runCall and runCode

### ISSUE THREAD

**Issue by axic** [ethereumjs/ethereumjs-vm#262]
https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/runBlock.js#L43-L56

`async.series` should be reorganised so that `afterBlock` is part of the series and is it not called with `parseBlockResult`.

In short the `async.series` should look like:
```
  async.series([
    beforeBlock,
    populateCache,
    processTransactions
    parseBlockResults,
    afterBlock
  ], cb)
```

**Comment by axic** [comment]
The same applies to `runCall` and `runCode`. For an example how to do it, see `runTx`.

**Comment by atkinsonholly** [comment]
@axic @holgerd77 I am taking a look at this as my first issue, is the above description up to date? Thanks!

**Comment by alcuadrado** [comment]
Hi @atkinsonholly. Thanks for your interesting in the project. I think this issue is no longer relevant, as `runBlock`, `runCall`, and `runCode` have been heavily refactored. Can you confirm this, @s1na ?

There's [this other issue](https://github.com/ethereumjs/ethereumjs-vm/issues/613) related to `runCall` and `runCode` that I opened a few weeks ago. I think that one can be a good first issue.

**Comment by s1na** [comment]
Hm, yeah `runBlock` and others been modified quite a bit since this issue was created. We can probably close this.

**Comment by atkinsonholly** [comment]
Thanks @alcuadrado I'll look at the other issue you suggested.

**Comment by alcuadrado** [comment]
> We can probably close this.

Agreed. This is just confusing now. I'll close this issue.
