### ISSUE TITLE
[Constantinople] EIP 1283 SSTORE net metering

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#354]
[EIP 1283](https://eips.ethereum.org/EIPS/eip-1283) SSTORE net metering without dirty maps (replaces EIP-1087)

Test Situation:
Open PR, affecting lots of tests
https://github.com/ethereum/tests/pull/511
https://github.com/ethereum/tests/issues/483

Implementation in the VM:
Mostly/all in the [SSTORE](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L362) opcode code.

**Comment by holgerd77** [comment]
No idea yet, we'll have to work this out together.

**Comment by holgerd77** [comment]
@yann300 Update: haven't looked deeper, but is ``stateManager.getContractStorage()`` already [used](https://github.com/ethereumjs/ethereumjs-vm/blob/master/lib/opFns.js#L377) in the opcode not already doing this?

**Comment by vpulim** [comment]
as @yann300 mentioned, ``stateManager.getContractStorage()`` only gets the current storage. I submitted a PR (#367) that sets ``runState.originalState`` to a copy of the ``stateManager`` trie so that it can later be used in the SSTORE opcode to read the original storage values. There may be a more efficient way to do this, but it will likely require significant changes to the stateManager implementation.

**Comment by holgerd77** [comment]
@vpulim For now this should work, better to have these updates ready in time for the dev tools to be used that start with complex ``StateManager`` refactorings.
