### ISSUE TITLE
Possible bug in `setStateroot` and caching

### ISSUE THREAD

**Issue by davidmurdoch** [ethereumjs/ethereumjs-vm#417]
I've created a test case [here](https://github.com/davidmurdoch/ethereumjs-vm/commit/150cec286059aab989f9597c2d357b6585f9c737#diff-898e9a9a2c99d28951c46c1145f3f3f1R50) to demonstrate what may be a bug in `setStateRoot`.

Ganache currently needs to run the VM with miscellaneous state roots, often with state roots from blocks prior to `"latest"`. We can use `vm.setStateRoot(miscBlock.header.stateRoot, cb)` to do this and it does work to set the stateRoot itself. However, the cache is getting in the way of actually using the values in this root.

Calling `vm.stateManager._cache.flush` and `vm.stateManager._cache.clear` before calling `setStateRoot` does the trick, but I'd rather not have to reach in to the (now) private `_cache` object.

I expected `setStateRoot` to clear/invalidate the cache itself..

**Comment by mattdean-digicatapult** [comment]
The `stateManager` implementation will flush the cache prior to setting the state root and ensures the new state root exists in the trie. An error will be returned via the callback if the cache cannot be flushed due to checkpointing or if the new state root doesn't exist. So I'm somewhat confused, is `setStateRoot` in your test returning any errors?

**Comment by davidmurdoch** [comment]
No, no errors. When the cache is `flush()`ed the entries remain in the cache; they are not cleared/evicted. So calls to get data out of the trie hit the cache, even though the cache contains stale data.

**Comment by mattdean-digicatapult** [comment]
OK I understand now. I'll try to have a look at this one
