### ISSUE TITLE
Some VM operations unexpectedly modify the state

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#559]
I figured a few days ago that `VM#runCall` modifies the state. I was quite sure that it didn't as I thought it resembled the nodes' RPC `eth_call`. I think we should document this in every VM operation.

**Comment by s1na** [comment]
Isn't one of the main purpose of running EVM contracts modifying the state? :) I'm not sure how this is unexpected, or how it could be otherwise!

**Comment by alcuadrado** [comment]
Maybe I'm confused by the name `runCall`. But I normally think of calls as executing an EVM code just to get its result, not to modify the state.

**Comment by holgerd77** [comment]
I generally think that the very most cases of initial confusion one has (especially people who already digged deeper into the code) have some solid ground respectively reasoning and it makes a lot of sense to directly direct this into some action - like add to the docs, rename stuff (would be overblown here) or think about the underlying structure.

It's pretty likely that less involved people will fall about stuff like this as well and these kind of improvements should over time significantly improve code and doc readability.

Will otherwise close the issue itself for now, @alcuadrado feel free to do a short PR on this.

**Comment by s1na** [comment]
> Maybe I'm confused by the name runCall. But I normally think of calls as executing an EVM code just to get its result, not to modify the state.

Sorry missed this yesterday.

I can imagine the name can be confusing. Many of the EVM opcodes modify the state, most clearly `SSTORE` which directly writes to the storage of a contract. Unless we do a checkpoint and revert before and after `runCall`, but in my opinion that'd be even more confusing. If you need an immutable version of `runCall` maybe we could add it as a new function?
