### ISSUE TITLE
Job testBlockchainPetersburg runs zero assertions

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#620]
As can be shown on [this false positive job](https://circleci.com/gh/ethereumjs/ethereumjs-vm/7533), it `test_blockchain_petersburg` failed to source test cases from ethereum/tests.

Test output:
```
1..0
# tests 0
# pass  0
```

That's probably a side-effect of the recent directory change of this [ethereum/tests release](https://github.com/ethereum/tests/releases/tag/v7.0.0-beta.1).

Skimming the code quickly, I find this to be the main reason these tests are not being found: [tests/tester.js:217-221](https://github.com/ethereumjs/ethereumjs-vm/blob/970ddbfe082a74ef397083f62de177eb2fd84a78/tests/tester.js#L217-L221)

It could be solved by [comparing hardforks](https://github.com/ethereumjs/ethereumjs-common/blob/9e624f86107cea904d8171524130d92c99bf9302/docs/classes/common.md#hardforkgtehardfork), instead of only testing for equality.

**Comment by ryanio** [comment]
I can confirm the issue locally:

<img width="923" alt="Screen Shot 2019-11-20 at 10 05 25 PM" src="https://user-images.githubusercontent.com/22116/69311726-e5d96c00-0be1-11ea-8bd2-b61d313c507d.png">

However, from my poking around it looks like the issue is because `ethereumjs-testing`'s `ethereum/tests` submodule folder is using [tests @ cfbcd15](https://github.com/ethereum/tests/tree/cfbcd15f91d4d6e1785d9cae5c5c37f47e8bad46), which for some reason its [LegacyTests/Constaninople/BlockchainTest](https://github.com/ethereum/tests/tree/cfbcd15f91d4d6e1785d9cae5c5c37f47e8bad46/LegacyTests/Constantinople/BlockchainTests) folder has only one subfolder `GeneralStateTests` thus missing subfolders `ValidBlocks` and `InvalidBlocks` such as in [tests @ develop](https://github.com/ethereum/tests/tree/develop/LegacyTests/Constantinople/BlockchainTests).

`GeneralStateTests` gets excluded in the npm script with `--excludeDir='GeneralStateTests'`, so it has no tests left to evaluate.

**Comment by s1na** [comment]
Good catch!

@holgerd77 I think at some point you mentioned you're planning a stable release of the `ethereum/tests`. Do you maybe have a timeline on that?

**Comment by holgerd77** [comment]
@s1na Hmm, I am not in charge of implementing changes on `ethereum/tests` myself and just drop by every now and then to look up on the evolution of the repository. In doubt open issues directly there or ask @winsvega.

**Comment by winsvega** [comment]
The Petersburg state tests of blockchain format are at

https://github.com/ethereum/tests/tree/develop/LegacyTests/Constantinople/BlockchainTests/GeneralStateTests

**Comment by s1na** [comment]
We're interested in the `ValidBlocks` and `InvalidBlocks` blockchain tests and the problem we're facing is that in the `v7.0.0-beta.1` release the [LegacyTests/Constantinople/BlockchainTests](https://github.com/ethereum/tests/tree/v7.0.0-beta.1/LegacyTests/Constantinople/BlockchainTests) directory only contains the state tests in blockchain format, and not `ValidBlocks` and `InvalidBlocks`.

We either have to wait for the next release of `ethereum/tests` or point directly to a commit on the `develop` branch.

**Comment by winsvega** [comment]
Oh. That splited on tests::develop branch. 
On released 7.0.0. beta branch  the Frontier...constantinopleFix bc tests are not sealed and could be found in https://github.com/ethereum/tests/tree/v7.0.0-beta.1/BlockchainTests

for updated testing I would recommend use the develop branch
