### ISSUE TITLE
runBlock gives less gasUsed than runTx

### ISSUE THREAD

**Issue by asinyagin** [ethereumjs/ethereumjs-vm#64]
Hi,

As I see, `runBlock()` gives wrong `gasUsed` while `runTx()` uses correct number of gas. Here's how to reproduce it: https://github.com/asinyagin/ethereumjs-test/blob/master/app.js . The app prints:
```
root@982421ef3b07:~/ethereumjs-test# node app.js 
tx: 5a24e
block: 05254e
```

**Comment by axic** [comment]
Does `runTx` gives the correct number compared to geth/ethereumj?

**Comment by asinyagin** [comment]
yeah, the live network uses the same number of gas as `runTx`

**Comment by axic** [comment]
The difference seems to be 32000 which is the cost of CREATE. There might be something off in block vs. tx regarding deploying a contract.

cc @wanderer

**Comment by wanderer** [comment]
so to recap I bet this is also the creation cost of a precompiled. @axic added an option to active the [precompiles](https://github.com/ethereumjs/ethereumjs-vm#new-vmstatetrie-blockchain) @asinyagin can you give that a try?

**Comment by asinyagin** [comment]
@axic I'm not sure. That's Ballot contract from https://ethereum.github.io/browser-solidity/#version=soljson-latest.js compiled with solc 0.3.0.

**Comment by asinyagin** [comment]
@wanderer it gives the same gasUsed with the key. Is the code correct? https://github.com/asinyagin/ethereumjs-test/blob/master/app.js#L37

**Comment by flyswatter** [comment]
I'm also experiencing out of gas errors, I think it may be related to this. Particularly, I'm getting OOG errors on transactions estimated by `testrpc` (which relies on `ethereumjs-vm`).

[The bug is documented on the testrpc github here](https://github.com/ethereumjs/testrpc/issues/86) and includes a test case.

**Comment by flyswatter** [comment]
Even better and more specific reproduction steps [in this testrpc issue, #96](https://github.com/ethereumjs/testrpc/issues/96).

**Comment by kumavis** [comment]
playing out the repro here with some deeper logging https://github.com/ethereumjs/testrpc/issues/96
while the trace is exactly the same, the gas calc divergence can be seen near the end https://www.diffchecker.com/7w3djc6a

**Comment by wanderer** [comment]
@kumavis so its messing up on the `SSTORE` on line 148

**Comment by kumavis** [comment]
ah ok
somehow the dynamic cost is calc'd wrong

**Comment by kumavis** [comment]
> © 2015 DiffChecker, Inc.
lel

**Comment by kumavis** [comment]
turns out my issue was unrelated -- was an issues in testrpc's provider-engine https://github.com/ethereumjs/testrpc/issues/96

**Comment by wanderer** [comment]
@asinyagin The problem is here https://github.com/asinyagin/ethereumjs-test/blob/master/app.js#L75 There is a cost difference between homestead and pre-homestead to create an account. By default tx's are homestead, but by setting the block number to 0 you force it to run as pre-homestead.

I added a check in 475143f87103a1fab12eed84e94da6526e58aada that should fix teh problem if you give the VM the option `opts:{enableHomestead: true}`

**Comment by wanderer** [comment]
@asinyagin please reopen if this if its still an issue

**Comment by asinyagin** [comment]
@wanderer thanks! it works great
