### ISSUE TITLE
Dev version installation fails on node v12

### ISSUE THREAD

**Issue by rumkin** [ethereumjs/ethereumjs-vm#661]
Development version of VM installation fails on node v12. The problem is caused by levedown native module compilation failure. Leveldown is a dependency of level package and according to it [readme](https://www.npmjs.com/package/leveldown) it isn't support current node version.

## Reproduce

1. Install node v12.
2. Clone repo.
3. Run `npm i .` inside of repository directory.

## Solution

Upgrade level package to the latest version.

## Checklist

- [x] Update `level` to `v6.0.0`.
- [ ] Update `level-mem` to `v6.0.0` here and into `ethereumjs-blockchain` package, after monorepo migration.

**Comment by holgerd77** [comment]
The `level` dependency is [used in the blockchain test runner](https://github.com/ethereumjs/ethereumjs-vm/blob/9e7dc98a434fb38a627159f0c1b28633edfba480/tests/BlockchainTestsRunner.js#L8) which passes on an instance to the `Blockchain` object as its DB.

`ethereumjs-blockchain` is using `level-mem` with a `v3.0.1` dependency (see [package.json](https://github.com/ethereumjs/ethereumjs-blockchain/blob/master/package.json#L51)), so also an older version.

I think it would make sense to keep this (relatively) in sync rather than update on one side and do an update both on the `VM` and `Blockchain` in one PR once we have both libraries together in the monorepo, what do you think @evertonfraga @ryanio?

**Comment by rumkin** [comment]
Level-family packages has the same interface and AFAIK backward compatible interfaces, so it seems safe and reliable to update only a single package. This update is required to fix node native package installation issue and as you can see in PR #662 all tests passed well even with the current `level-mem`. Current version of level breaks the installation so it seems reasonable to fix this and add an issue for mono-repo to update the rest of level related things.

**Comment by holgerd77** [comment]
Ok, that makes sense. Not that much of a level expert and always unsure on how conservative to be here in updates.

**Comment by evertonfraga** [comment]
Seems sensible to me to pack changes together in the monorepo.

**Comment by rumkin** [comment]
@evertonfraga There should be a label `package: blockchain` too. I'm going to update package `level-mem` for it too.

**Comment by holgerd77** [comment]
Fixed by #662
