### ISSUE TITLE
Making runCode Synchronous for pure functions

### ISSUE THREAD

**Issue by snario** [ethereumjs/ethereumjs-vm#677]
I'd like to use `ethereumjs-vm` for executing a `pure` function. However, `runCode` is `async` which is kind of annoying. Is there some way to allow for a synchronous call if the function being called is known to be `pure`?

**Comment by andrewgordstewart** [comment]
Here is one possible use case (specifically relevant to the state-channels project)
1. I am storing states in a state channel in indexedDB store
2. I would like to add a new state to the store. But before I add the state, I want to validate the transition.
3. I would like to validate the transition to the new state by calling a `pure` function using `ethereumjs-vm`. This way, I am validating the transition in the [same way](https://github.com/statechannels/monorepo/blob/a05c74090287d07c84ba67bf9191a33a5227eaa1/packages/nitro-protocol/contracts/ForceMove.sol#L521-L526) that an adjudicator smart contract of the state channel would.
4. I would like to validate the transition within an indexedDB transaction, so that I know that the "previous" state is the most recent state.

3 & 4 are more or less incompatible, given the indexedDB API -- the transaction would throw a `TransactionInactiveError`.

It is possible to use something like [Dexie.waitFor()](https://dexie.org/docs/Dexie/Dexie.waitFor()) to await the async `pure` function call within the transaction, if you really want to. But, as mentioned in this link, there can be a substantial performance hit due to the implementation of `waitFor`. (I have not checked if the `pure` function call would take a long enough time to resolve to matter.)

If the `waitFor` hack is too CPU intensive, then I would have to settle for validating transitions outside of a database transaction, which I would probably classify as **annoying**, but not a complete dealbreaker.

**Comment by jochem-brouwer** [comment]
This is an interesting issue. I do not think this is possible. Reason: we do not know beforehand if the executed function is `pure` or not. Of course we can scan the code and see that the code itself does not contain any async code. But this is only a small subset of code: if you would pick any contract it is highly likely that there are asynchronous operations in them. 

What if we add a `runCodeSync` function? This throws if it hits any async operation?

**Comment by snario** [comment]
> What if we add a `runCodeSync` function? This throws if it hits any async operation?

Sounds great!

**Comment by jochem-brouwer** [comment]
Hmm okay this would actually need a complete overhaul of the EVM since most of the interpreters' functions are `async`. If someone has a good suggestion on how to cleanly convert `async` code to synchronous then that'd be appreciated. If I would implement it now I would copy huge chunks of code and removing all `async` keywords, which is obviously a very bad practice (the copying code part).

**Comment by alcuadrado** [comment]
@snario @andrewgordstewart you may find this project useful: https://github.com/armaniferrante/pure-evm It uses parity's evm compiled to wasm. You can run pure functions synchronously there. It doesn't include precompiles, but [Connext has a fork](https://github.com/connext/pure-evm) that includes some of them.

**Comment by alcuadrado** [comment]
> Hmm okay this would actually need a complete overhaul of the EVM since most of the interpreters' functions are `async`. If someone has a good suggestion on how to cleanly convert `async` code to synchronous then that'd be appreciated. If I would implement it now I would copy huge chunks of code and removing all `async` keywords, which is obviously a very bad practice (the copying code part).

The issue is that as soon as one of your functions is `async`, most of your code needs to be a `async`, and the StateManager is. I think js people call this [function coloring](https://journal.stuffwithstuff.com/2015/02/01/what-color-is-your-function/) or something like that.

**Comment by snario** [comment]
Yes Armani used to work with us :) We’ve been using this project. However, WebAssembly adds an additional level of complexity that doesn’t need to be there since we have this JS based implementation.

**Comment by alcuadrado** [comment]
I think Connext was also having issues with wasm when trying to use it.

To be honest I think the effort to implement a new subset of the EVM that just runs pure functions is much smaller than adapting this one. If you don't care about gas at all (i.e. no counting nor OOG errors), hard fork selection, and external calls, implementing an EVM is pretty straightforward. I implemented one a few weeks ago to learn some rust, and was surprised about how simple it was. 

Not to say that you should do it, but if someone were to try to make a sync version of this EVM just to run pure functions, they should first consider this other option.

**Comment by holgerd77** [comment]
Regarded as too complex to implement after discussion, will close.
