### ISSUE TITLE
Use constant for default hardfork

### ISSUE THREAD

**Issue by ryanio** [ethereumjs/ethereumjs-vm#822]
@alcuadrado noted in https://github.com/ethereumjs/ethereumjs-vm/pull/812#discussion_r458417070 that we should probably use a constant for the default hardfork, currently set across the monorepo as `'petersburg'`.

I don't think `@ethereumjs/common` is currently set up to handle multiple exports, but if that is changed then we can export a constant like `DEFAULT_HARDFORK`. I am open to other ideas, and also happy to take on this PR.

**Comment by jochem-brouwer** [comment]
Isn't it an idea to change the function signature of the constructor of `Common` from:

`new Common(chain: string | number | object, hardfork?: string | null, supportedHardforks?: Array‹string›)`

to:

`new Common(chain?: string | number | object, hardfork?: string | null, supportedHardforks?: Array‹string›)`

(i.e. `chain` is now optional).

In case you would then call `new Common()` it would then return `DEFAULT_HARDFORK`.

**Comment by holgerd77** [comment]
@jochem-brouwer that sounds a bit hacky to me TBH, Common is also only really useful with a chain associated, otherwise most of the functionality won't work.

I also think it is likely something between useful and necessary to be able to differentiate on the default HF per chain, since there are sometimes situations where one chain jumps on a specific fork (DAO on mainnet e.g.) which other chains omit. On other situations there might be a bigger time gap between the HF swich on the one and the other chain and one might want to set different default HFs for some time. Third thing is the situation for custom chains, there might be totally different default HFs needed.

I think it might be worth to consider to initialize with the default HF (stored internally likely within the chain JSON file (e.g. `mainnet.json`) when the constructor is used without a fork, e.g. `new Common('ropsten')`. This would also make the code base more robust, currently several functions throw - all the ones who are calling [_chooseHardfork](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/common/src/index.ts#L132) internally when they are called within a non-HF-set context. So behavior gots a lot more "deterministic" when a HF is always set.

This might have also its dangers though if people might not be so much aware on which fork they are atm, so not completely sure on this.

---

I also wonder (related side thought) if we should expand on the constructor like:

```javascript
new Common(chain: string | number | object, hardfork?: string | number | null, supportedHardforks?: Array‹string›)
```

and allowing a `number` input for the `hardfork` where it is possible to just provide the block number and the hardfork is then set by the fork determined. This would also help on this tx initialization crash problem https://github.com/ethereumjs/ethereumjs-vm/pull/756 I guess.

**Comment by ryanio** [comment]
resolved with https://github.com/ethereumjs/ethereumjs-vm/pull/863#discussion_r486541847
