### ISSUE TITLE
Many libraries have really poor error management

### ISSUE THREAD

**Issue by alcuadrado** [ethereumjs/ethereumjs-vm#844]
I'm starting to use `-vm`, `-block` and `-blockchain` a lot, and I'm constantly struggling to debug things because strings are passed instead of errors.

This is a good example of a function that is a nightmare to work with: https://github.com/ethereumjs/ethereumjs-block/blob/master/header.js#L207

The simplest way to solve this is to use `new Error("existing string")` instead of `"existing string"` everywhere. Making sure that it's actually fixed **everywhere** is a perfect example of something achievable in a couple of hours in a monorepo, but that would take a lot of time to coordinate across multiple repos.

**Comment by holgerd77** [comment]
Have moved this issue over to the monorepo since all libraries referenced are part of it.

It would be good if someone could give the current state on error management of the different monorepo libraries (did error management improve? to what extend? which libraries are in what kind of needs?) some analysis and write-up here.

There also happened some thinking around this along #487 opened by @rumkin, but this hasn't been followed by some execution yet. This can also be taken into account respectively serve as some inspiration for a more coherent strategy on the question of error handling.

**Comment by ryanio** [comment]
I think this may have been resolved along with the TS transition/refactorings.

Looking at [header.ts](https://github.com/ethereumjs/ethereumjs-vm/blob/master/packages/block/src/header.ts#L268) now, all the errors are thrown with `new Error('error message')` as opposed to e.g. `cb('error message')` in the old [header.js](https://github.com/ethereumjs/ethereumjs-block/blob/v2.0.1/header.js#L220).

**Comment by holgerd77** [comment]
Ok, since this issue is a bit blurry on the scope, I will close this one and have instead renamed #487 to reflect a more generic error management improvement. There are also already a lot of analysis and improvement ideas written down.
