### ISSUE TITLE
Remove Block dependency from BlockHeader Class

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#915]
The `BlockHeader` class has a dependency to the `Block` class which is structurally suboptimal since it introduces a (currently non-breaking, but nevertheless) circling dependency.

This can be solved by passing the `parentBlockHeader` instead of the `parentBlock` to the following functions:

- `canonicalDifficulty(parentBlock: Block): BN`
- `validateDifficulty(parentBlock: Block): boolean`
- `validateGasLimit(parentBlock: Block): boolean`

This can be done without structural changes within the methods since all these methods directly or indirectly only use `parentBlock.header` anyhow.

//cc @jochem-brouwer @ryanio

**Comment by jochem-brouwer** [comment]
Yes this sounds like a great idea. Header should not depend on block. This might be slightly more work than anticipated, since it is likely that this is widely used in tests.

Is it an idea to add these functions in `Block` aswell, which simply call into `this.header.<method>`? I.e. `block.validateDifficulty(parentBlock)`?
