### ISSUE TITLE
Analyze BlockHeader -> Block Inheritance Introduction Possibility

### ISSUE THREAD

**Issue by holgerd77** [ethereumjs/ethereumjs-vm#916]
Depends on #915 

I am currently  not sure if we can easily introduce inheritance here (and if we generally want to, are there any downsides?) without breaking up the current refactoring structure again.

One eventually possible pattern I came up with:

1. Add the possibility to pass an optional `Block` instance created in the respective `Block` factory methods to the `BlockHeader` factories. 
2. Call the `super()` constructor in this case from the `BlockHeader` factories (can this be called from the outside?) and return the `Block` object
3. The fitting static `BlockHeader` factories are then called with the created `Block` instance from within the `Block` static factories
3. The `header` parameter from the `Block` constructor is removed

I would say on first thought that this should end up as a consistent solution. Needs some confirmation though.

//cc @jochem-brouwer @ryanio @cgewecke

**Comment by jochem-brouwer** [comment]
I am not sure here. Wouldn't this clog the constructor of `Header` a lot if we also allow to add parameters for the `Block constructor`?

**Comment by jochem-brouwer** [comment]
Wouldn't it make more sense to make Block inherit Header? Block is basically a header with the associated data (i.e. the actual uncles and the actual transactions instead of the hashes), so it would make sense to extend Header with Block. (so `Block extends Header`. 

This would semantically mean that `Header` is a raw `Header` and `Block` is a `Header` with the associated (non-hashed/packed) data. I think this was meant in the first place, especially with @alcuadrado mentioning at some point that `Header` was created with light clients in mind (they generally do not care about the data in the `Block` and just want the `Header`s).

However this would mean that we dispose the `.header` property of `Block` which is a rather drastic change 🤔

**Comment by holgerd77** [comment]
Ah, everything I write here is to make this possible, so `Block extends Header`. That's the whole point of this issue. 😛

**Comment by jochem-brouwer** [comment]
Right, I mixed up the terminology here, got confused by `BlockHeader` 😅

**Comment by holgerd77** [comment]
If the `header` property is a problem we might just return `this` on a `header` getter, that should preserve the functionality. But doing the static instantiation is a bit more tricky, therefore the suggestion above.

**Comment by holgerd77** [comment]
Did some more reflection on this and came to the conclusion that this might actually not be desired to have such tight coupling here since it prevents constructs like doing Header  subclasses, e.g. if on some EIP some functionality is added to the classical header and we want to do a BlockHeaderEIP12345 subclassing (already expressed that in the chat).

Will close this for now. If someone wants to reopen the discussion in some PIT feel free to reopen the issue.
