### ISSUE TITLE
Time to revive the `test:vm`?

### ISSUE THREAD

**Issue by evertonfraga** [ethereumjs/ethereumjs-vm#954]
I just saw that in the packages/vm/developer.md file: 

> VM tests are disabled since Frontier gas costs are not supported any more.

**Comment by holgerd77** [comment]
I have read some time ago in some `ethereum/tests` context (an issue on the repo? chat?) that VM tests are deprecated and should be integrated into the state tests. This would need confirmation though.

//cc @winsvega

**Comment by winsvega** [comment]
the discusssion after that concluded that there are teams who really like the vm tests as they are. as it is convinient to develop a raw vm, the one without states, call logic, the blockchain stuff.

the thing is that vm tests are outdated (since Frontier) and has some basic VM coverage.

The bytecode from VM tests is converted to blockchain tests and run on Hive. 

If there is a need to revive VMTests I am up for it. the only client that was capable of generating the vm tests was testeth. 
I think we can add this support to geth t8ntool as it is already a detached vm that generates all the tests now.

**Comment by holgerd77** [comment]
@winsvega ah, thanks for the update, thanks! 👍 

From our side there is no pressing need to revive the VM tests I would say atm.

**Comment by winsvega** [comment]
How would you like to see the VM Tests? What are the requirements?
Why StateTests are not suitable for evm testing?

**Comment by holgerd77** [comment]
@winsvega I don't have a strong opinion on that, I think this issue opened by @evertonfraga was just rather meant as some "nice to have" but we otherwise haven't dealt with the VM tests in the last years.

One argument for VM tests is that this tests a lot more specific functionality and it is a lot easier to track what is actually broken, e.g. if you just do some arithmetic test like [add0.json](https://github.com/ethereum/tests/blob/develop/VMTests/vmArithmeticTest/add0.json). On state and - even more - tests always "the whole thing" is run and debugging failures is a lot harder. VM tests are (somewhat) more like unit tests, state and blockchain tests like integration tests.

So I would generally agree that both test types are useful.

**Comment by winsvega** [comment]
It seems to me that there is little to no difference between this 2 formats. I assume it is convertible one into another.

As far as I remember VM test does not support calls. Other then that its like a state test

**Comment by qbzzt** [comment]
> It seems to me that there is little to no difference between this 2 formats. I assume it is convertible one into another.
> 
> As far as I remember VM test does not support calls. Other then that its like a state test

I agree. I don't think we should resurrect VMTests. Instead, we can take GeneralStateTests, which are updated, and turn them into a format the evm developers can use. That way we don't have two repositories of tests that do almost exactly the same thing.

If I understand it correctly, evm developers need a format that has the initial storage, the byte code (possibly of multiple addresses), the final storage, and the transaction that triggers it. Is that correct?

**Comment by qbzzt** [comment]
> the discusssion after that concluded that there are teams who really like the vm tests as they are. as it is convinient to 
> develop a raw vm, the one without states, call logic, the blockchain stuff.

Call logic I understand, but how would you develop a raw VM without storage? What would you use to identify the program ran correctly?

**Comment by winsvega** [comment]
That called vm trace. It can be exported when running a state test as well. Casey was doing the vm trace log standardization among clients.

**Comment by qbzzt** [comment]
How about we put the vm trace with the filled state tests (either in the
same file or a different file with a related name)? That way people who
make VMs will be able to run their own vm trace, and see where things go
wrong.

**Comment by winsvega** [comment]
it does not make sense as it would be gigabytes of data. all you need is just a client and retesteth --vmtrace command. which now comes a handy docker with documentation.

**Comment by qbzzt** [comment]
> and if you configure a reference client and a test client retesteth can compare 2 traces and show the difference.

Good point. How do I do it? Should we have a tutorial to teach how to instrument your evm so it will work with it? I think that can be used to make the state tests into what are effectively vmtests.

**Comment by winsvega** [comment]
we already done it. it is a RPC test protocol here: https://github.com/ethereum/retesteth/wiki/RPC-Methods
or transition tool protocol here: https://github.com/ethereum/retesteth/wiki/Transition-Tool
and the manual: https://ethereum-tests.readthedocs.io/en/latest/retesteth-tutorial.html#test-against-your-client

**Comment by winsvega** [comment]
I think we can be sufficient enough with just the state tests. I mean if poststate calculation is too heavy for raw vm implementation, we can put gasUsage in a generated state test and compare vm trace logs.

**Comment by holgerd77** [comment]
Thanks guys for joining this discussion so actively, will close this issue for now.
